# permissions to do viewer reproes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repro-viewer-role
rules:
- apiGroups:
  - left.play.zone
  resources:
  - reproes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - left.play.zone
  resources:
  - reproes/status
  verbs:
  - get
